version: '3.8'

services:
  runner:
    image: youssefbrr/github-actions:latest # You can use this image or build your own
    restart: always
    environment:
      - REPO=<owner>/<repo>
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=<runner-name>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - <path-to-your-github-actions-runner-workdir>:/home/docker/actions-runner/_work
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M